/**
 * UI strings in English and Polish. Pure data, shared by the browser
 * (js/i18n.js) and the static page generator (scripts/build-static.mjs).
 */

export const STRINGS = {
    en: {
        'start.portfolio': 'Portfolio',
        'start.contact': 'Contact Me',
        'start.projects': 'Projects',
        'start.network': 'Network',
        'start.explorer': 'File Explorer',
        'start.notepad': 'Notepad',
        'start.paint': 'Paint',
        'start.terminal': 'Terminal',
        'start.calc': 'Calculator',
        'start.internet': 'Internet',
        'start.simple': 'Simple View',
        'start.mines': 'Minesweeper',
        'start.tunes': 'Tunes',
        'start.sysinfo': 'System Info',
        'start.taskmgr': 'Task Manager',
        'start.settings': 'Settings',
        'start.help': 'Help',

        'lang.switch': 'Język: polski',
        'lang.current': 'Language: English',

        'privacy.title': 'Privacy Settings',
        'privacy.heading': 'This website uses local storage',
        'privacy.body': 'We save your preferences, window positions, and session data locally to improve your experience. No data is sent to external servers.',
        'privacy.decline': 'You can decline if you prefer not to have your session saved.',
        'privacy.accept': '✓ Accept',
        'privacy.declineBtn': '✗ Decline',

        'section.about': 'About Me',
        'section.experience': 'Experience',
        'section.skills': 'Skills',
        'section.projects': 'Projects',
        'section.education': 'Education',
        'section.contact': 'Contact',
        'cv.about': 'About',
        'cv.save': 'Save as PDF',
        'portfolio.downloadCv': 'Download CV',
        'portfolio.sendMessage': 'Send Message',
        'portfolio.openProjects': 'Open Projects application',
        'simple.toolbar': 'Plain HTML Portfolio View',
        'simple.print': 'Print',
        'simple.footer': 'Generated with Portfolio OS.',

        'projects.heading': 'Projects',
        'projects.by': 'Public repositories by',
        'projects.repositories': 'repositories',
        'projects.openGithub': 'Open GitHub',
        'projects.find': 'Find a project',
        'projects.placeholder': 'Name or description…',
        'projects.allLanguages': 'All languages',
        'projects.count': '{count} shown',
        'projects.empty': 'No projects match this filter.',
        'projects.featured': 'Featured',
        'projects.noLicense': 'No license listed',
        'projects.updated': 'Updated',
        'projects.details': 'Details',
        'projects.sourceLive': 'Live data from {link}. Click a project to read its README.',
        'projects.sourceOffline': 'Could not load live data from GitHub - showing a saved snapshot of {link}.',
        'projects.sourceSnapshot': 'Snapshot based on {link}.',

        'viewer.loading': 'Loading README…',
        'viewer.noReadme': 'This repository has no README yet.',
        'viewer.error': 'Could not load the README from GitHub.',
        'viewer.openRepo': 'Open on GitHub',
        'viewer.back': 'All projects',
        'viewer.stars': 'stars',

        'network.title': 'Network Neighborhood',
        'network.subtitle': 'Services I host and maintain myself',
        'network.host': 'Host',
        'network.uptime': 'Uptime',
        'network.load': 'Load',
        'network.memory': 'Memory',
        'network.online': 'Online',
        'network.offline': 'Offline',
        'network.checking': 'Checking…',
        'network.checked': 'Last check',
        'network.refresh': 'Refresh',
        'network.unavailable': 'The status service is not available on this deployment.',
        'network.open': 'Open',
        'network.days': 'd',
        'network.hours': 'h',
        'network.minutes': 'min',

        'contact.heading': 'Get In Touch',
        'contact.intro': "Send me a message and I'll get back to you!",
        'contact.name': 'Your Name:',
        'contact.email': 'Email Address:',
        'contact.subject': 'Subject:',
        'contact.message': 'Message:',
        'contact.messagePlaceholder': 'Type your message here...',
        'contact.subject.general': 'General Inquiry',
        'contact.subject.job': 'Job Opportunity',
        'contact.subject.project': 'Project Collaboration',
        'contact.subject.feedback': 'Feedback',
        'contact.subject.bug': 'Bug Report',
        'contact.send': 'Send Message',
        'contact.clear': 'Clear',
        'contact.sending': 'Sending message...',
        'contact.sent': 'Message Sent!',
        'contact.thanks': 'Thanks',
        'contact.willRespond': "I'll respond to {email} as soon as possible.",
        'contact.yourMessage': 'Your message:',
        'contact.sendAnother': 'Send Another',
        'contact.failed': 'Failed to Send',
        'contact.timeout': 'The request timed out. Please try again.',
        'contact.genericError': 'Something went wrong. Please try again.',
        'contact.tryAgain': 'Try Again',

        'readme.welcome': 'Welcome to my digital portfolio!',
        'readme.intro': ['This operating system was created', 'to showcase my web development', 'skills in an interactive way.'],
        'readme.howTo': 'HOW TO USE:',
        'readme.howToItems': ['• Double click = open application', '• Drag window = move it around', '• Buttons [-][□][×] = window controls', '• Start Menu = access everything', '• EN/PL in the taskbar = language'],
        'readme.apps': 'AVAILABLE APPLICATIONS:',
        'readme.appItems': ['📁 PORTFOLIO.EXE - My projects & bio', '📂 PROJECTS.EXE - Live GitHub repos', '🌐 NETWORK.EXE  - Status of my servers', '📝 NOTEPAD.EXE  - Notepad with save', '🎵 TUNES.EXE    - Background music', '💣 MINES.EXE    - Classic Minesweeper', '🐍 SNAKE.EXE    - Classic Snake', '🧱 TETRIS.EXE   - Classic Tetris', '🎨 PAINT.EXE    - Draw & paint', '🖩 CALC.EXE     - Calculator', '💻 TERMINAL.EXE - Command line', '📊 TASKMGR.EXE  - Task Manager', '📂 EXPLORER.EXE - File browser', 'ℹ️ SYSINFO.EXE  - System info', '📧 CONTACT.EXE  - Contact form', '⚙️ CONTROL.CPL  - Control Panel'],
        'readme.themes': 'THEMES:',
        'readme.themeItems': ['Available in Control Panel:', 'Teal, Dark, Hotdog Stand, Matrix,', 'Clouds, Win95, Win98, macOS, Ubuntu', '+ Auto-theme (dark mode 19:00-7:00)'],
        'readme.secrets': '🔐 HIDDEN SECRETS (SPOILER)',

        'static.notice': 'JavaScript is turned off, so this is the lightweight version of Portfolio OS. Turn JavaScript on for the full interactive desktop.',
        'static.interactive': 'Open the interactive version',
        'static.otherLanguage': 'Polski',
        'static.cv': 'CV',
        'static.allProjects': 'All projects on GitHub',
        'static.contactIntro': 'Send me a message or reach me directly:',
        'static.formNote': 'The form works without JavaScript.',
        'static.formNeedsJs': 'The contact form needs JavaScript (it uses an anti-spam check). Without it, please write to:',
        'static.mode': 'Static mode',
        'static.skip': 'Skip to content',
        'cv.printHint': 'Use your browser print dialog (Ctrl+P) and choose "Save as PDF".',
        'cv.back': '← Back to portfolio',
        'cv.otherLanguage': 'Wersja polska',
        'sent.title': 'Message sent',
        'sent.body': "Thanks for your message. I'll get back to you as soon as possible.",
        'error.title': 'Message not sent',
        'error.body': 'Something went wrong or too many messages were sent recently. Try again later or email me directly.',
        'sent.back': '← Back to portfolio',
        'notfound.title': '404 - File not found',
        'notfound.body': 'This page does not exist. Maybe it was deleted, or it never existed.',
        'section.interests': 'Interests',
        'cv.profile': 'Profile',
        'cv.contact': 'Contact',
        'cv.portfolio': 'Portfolio',
        'cv.consent': '',
        'printer.status': 'Printing page 1 of 1…',
        'printer.done': 'Printing complete. Your CV is ready.',
        'printer.cancelled': 'Printing cancelled.',
        'printer.open': 'Open CV',
        'printer.cancel': 'Cancel',
        'printer.model': 'DOT-MATRIX 24',

        'browser.placeholder': 'Type an address, a YouTube link or words to search…',
        'browser.go': 'Go',
        'browser.timeMachine': 'Time machine',
        'browser.live': 'Live web',
        'browser.archived': 'This site does not allow being shown inside other pages, so this is its latest copy from the Wayback Machine.',
        'browser.archivedYear': 'Time machine: you are browsing the web as it looked in {year}.',
        'browser.openLive': 'Open the live site ↗',
        'browser.loading': 'Opening {host}…',
        'browser.done': 'Done',
        'browser.openedApp': 'Opened in {app}.',
        'browser.back': 'Back',
        'browser.forward': 'Forward',
        'browser.refresh': 'Refresh',
        'browser.home': 'Home',
        'home.welcome': "Welcome to {name}'s Home Page!",
        'home.marquee': '★ Thanks for stopping by! ★ Best viewed in Internet 3.1 at 800×600 ★ Sign my guestbook in Contact.exe ★ No cookies were harmed ★',
        'home.construction': 'UNDER CONSTRUCTION',
        'home.visitor': 'You have visited this page',
        'home.times': 'times',
        'home.about': 'About me',
        'home.projects': 'My projects',
        'home.cool': 'Cool links',
        'home.search': 'Search Wikipedia',
        'home.searchButton': 'Search',
        'home.tip': 'Tip: paste a YouTube, Spotify or Vimeo link into the address bar, or pick a year in the Time machine.',
        'home.updated': 'Last updated',
        'home.email': 'E-mail me',
        'home.webring': 'PortfolioOS Webring',
        'home.random': 'Random Wikipedia article',
        'home.google99': 'Google in 1999',
        'home.yahoo96': 'Yahoo! in 1996',
        'home.spacejam': 'Space Jam (1996)',
        'home.youtube05': 'YouTube in 2005'
    },

    pl: {
        'start.portfolio': 'Portfolio',
        'start.contact': 'Kontakt',
        'start.projects': 'Projekty',
        'start.network': 'Sieć',
        'start.explorer': 'Eksplorator plików',
        'start.notepad': 'Notatnik',
        'start.paint': 'Paint',
        'start.terminal': 'Terminal',
        'start.calc': 'Kalkulator',
        'start.internet': 'Internet',
        'start.simple': 'Widok prosty',
        'start.mines': 'Saper',
        'start.tunes': 'Muzyka',
        'start.sysinfo': 'Informacje o systemie',
        'start.taskmgr': 'Menedżer zadań',
        'start.settings': 'Ustawienia',
        'start.help': 'Pomoc',

        'lang.switch': 'Language: English',
        'lang.current': 'Język: polski',

        'privacy.title': 'Ustawienia prywatności',
        'privacy.heading': 'Ta strona korzysta z pamięci lokalnej',
        'privacy.body': 'Zapisujemy Twoje ustawienia, położenie okien i dane sesji lokalnie w przeglądarce. Żadne dane nie są wysyłane na zewnętrzne serwery.',
        'privacy.decline': 'Możesz odmówić, jeśli nie chcesz zapisywać sesji.',
        'privacy.accept': '✓ Akceptuję',
        'privacy.declineBtn': '✗ Odmawiam',

        'section.about': 'O mnie',
        'section.experience': 'Doświadczenie',
        'section.skills': 'Umiejętności',
        'section.projects': 'Projekty',
        'section.education': 'Wykształcenie',
        'section.contact': 'Kontakt',
        'cv.about': 'O mnie',
        'cv.save': 'Zapisz jako PDF',
        'portfolio.downloadCv': 'Pobierz CV',
        'portfolio.sendMessage': 'Napisz do mnie',
        'portfolio.openProjects': 'Otwórz aplikację Projekty',
        'simple.toolbar': 'Portfolio w prostym HTML',
        'simple.print': 'Drukuj',
        'simple.footer': 'Wygenerowano w Portfolio OS.',

        'projects.heading': 'Projekty',
        'projects.by': 'Publiczne repozytoria:',
        'projects.repositories': 'repozytoriów',
        'projects.openGithub': 'Otwórz GitHub',
        'projects.find': 'Znajdź projekt',
        'projects.placeholder': 'Nazwa lub opis…',
        'projects.allLanguages': 'Wszystkie języki',
        'projects.count': 'Widoczne: {count}',
        'projects.empty': 'Żaden projekt nie pasuje do filtra.',
        'projects.featured': 'Wyróżniony',
        'projects.noLicense': 'Brak licencji',
        'projects.updated': 'Aktualizacja',
        'projects.details': 'Szczegóły',
        'projects.sourceLive': 'Dane na żywo z {link}. Kliknij projekt, żeby przeczytać jego README.',
        'projects.sourceOffline': 'Nie udało się pobrać danych z GitHuba - pokazuję zapisaną listę z {link}.',
        'projects.sourceSnapshot': 'Lista zapisana na podstawie {link}.',

        'viewer.loading': 'Wczytywanie README…',
        'viewer.noReadme': 'To repozytorium nie ma jeszcze README.',
        'viewer.error': 'Nie udało się pobrać README z GitHuba.',
        'viewer.openRepo': 'Otwórz na GitHubie',
        'viewer.back': 'Wszystkie projekty',
        'viewer.stars': 'gwiazdek',

        'network.title': 'Otoczenie sieciowe',
        'network.subtitle': 'Usługi, które sam hostuję i utrzymuję',
        'network.host': 'Serwer',
        'network.uptime': 'Czas pracy',
        'network.load': 'Obciążenie',
        'network.memory': 'Pamięć',
        'network.online': 'Działa',
        'network.offline': 'Nie działa',
        'network.checking': 'Sprawdzam…',
        'network.checked': 'Ostatnie sprawdzenie',
        'network.refresh': 'Odśwież',
        'network.unavailable': 'Usługa statusu nie jest dostępna w tym wdrożeniu.',
        'network.open': 'Otwórz',
        'network.days': 'd',
        'network.hours': 'h',
        'network.minutes': 'min',

        'contact.heading': 'Napisz do mnie',
        'contact.intro': 'Wyślij wiadomość, a odpiszę najszybciej, jak się da!',
        'contact.name': 'Imię i nazwisko:',
        'contact.email': 'Adres e-mail:',
        'contact.subject': 'Temat:',
        'contact.message': 'Wiadomość:',
        'contact.messagePlaceholder': 'Wpisz tutaj swoją wiadomość...',
        'contact.subject.general': 'Pytanie ogólne',
        'contact.subject.job': 'Oferta pracy',
        'contact.subject.project': 'Współpraca przy projekcie',
        'contact.subject.feedback': 'Opinia',
        'contact.subject.bug': 'Zgłoszenie błędu',
        'contact.send': 'Wyślij',
        'contact.clear': 'Wyczyść',
        'contact.sending': 'Wysyłanie wiadomości...',
        'contact.sent': 'Wiadomość wysłana!',
        'contact.thanks': 'Dziękuję',
        'contact.willRespond': 'Odpowiem na {email} najszybciej, jak to możliwe.',
        'contact.yourMessage': 'Twoja wiadomość:',
        'contact.sendAnother': 'Wyślij kolejną',
        'contact.failed': 'Nie udało się wysłać',
        'contact.timeout': 'Przekroczono czas oczekiwania. Spróbuj ponownie.',
        'contact.genericError': 'Coś poszło nie tak. Spróbuj ponownie.',
        'contact.tryAgain': 'Spróbuj ponownie',

        'readme.welcome': 'Witaj w moim cyfrowym portfolio!',
        'readme.intro': ['Ten system operacyjny powstał,', 'żeby w interaktywny sposób pokazać', 'moje umiejętności programistyczne.'],
        'readme.howTo': 'JAK KORZYSTAĆ:',
        'readme.howToItems': ['• Podwójne kliknięcie = otwórz aplikację', '• Przeciągnij okno = przesuń je', '• Przyciski [-][□][×] = sterowanie oknem', '• Menu Start = dostęp do wszystkiego', '• EN/PL na pasku zadań = język'],
        'readme.apps': 'DOSTĘPNE APLIKACJE:',
        'readme.appItems': ['📁 PORTFOLIO.EXE - Projekty i bio', '📂 PROJECTS.EXE - Repozytoria z GitHuba', '🌐 NETWORK.EXE  - Status moich serwerów', '📝 NOTEPAD.EXE  - Notatnik z zapisem', '🎵 TUNES.EXE    - Muzyka w tle', '💣 MINES.EXE    - Klasyczny Saper', '🐍 SNAKE.EXE    - Klasyczny Wąż', '🧱 TETRIS.EXE   - Klasyczny Tetris', '🎨 PAINT.EXE    - Rysowanie', '🖩 CALC.EXE     - Kalkulator', '💻 TERMINAL.EXE - Wiersz poleceń', '📊 TASKMGR.EXE  - Menedżer zadań', '📂 EXPLORER.EXE - Przeglądarka plików', 'ℹ️ SYSINFO.EXE  - Informacje o systemie', '📧 CONTACT.EXE  - Formularz kontaktowy', '⚙️ CONTROL.CPL  - Panel sterowania'],
        'readme.themes': 'MOTYWY:',
        'readme.themeItems': ['Dostępne w Panelu sterowania:', 'Teal, Dark, Hotdog Stand, Matrix,', 'Clouds, Win95, Win98, macOS, Ubuntu', '+ Auto-motyw (ciemny 19:00-7:00)'],
        'readme.secrets': '🔐 UKRYTE SEKRETY (SPOILER)',

        'static.notice': 'JavaScript jest wyłączony, więc widzisz lekką wersję Portfolio OS. Włącz JavaScript, żeby zobaczyć pełny, interaktywny pulpit.',
        'static.interactive': 'Otwórz wersję interaktywną',
        'static.otherLanguage': 'English',
        'static.cv': 'CV',
        'static.allProjects': 'Wszystkie projekty na GitHubie',
        'static.contactIntro': 'Napisz wiadomość albo skontaktuj się bezpośrednio:',
        'static.formNote': 'Formularz działa bez JavaScriptu.',
        'static.formNeedsJs': 'Formularz kontaktowy wymaga JavaScriptu (korzysta z ochrony antyspamowej). Bez niego napisz na adres:',
        'static.mode': 'Tryb statyczny',
        'static.skip': 'Przejdź do treści',
        'cv.printHint': 'Użyj drukowania w przeglądarce (Ctrl+P) i wybierz „Zapisz jako PDF”.',
        'cv.back': '← Wróć do portfolio',
        'cv.otherLanguage': 'English version',
        'sent.title': 'Wiadomość wysłana',
        'sent.body': 'Dziękuję za wiadomość. Odpowiem najszybciej, jak to możliwe.',
        'error.title': 'Nie udało się wysłać wiadomości',
        'error.body': 'Coś poszło nie tak albo wysłano ostatnio zbyt wiele wiadomości. Spróbuj później albo napisz do mnie bezpośrednio.',
        'sent.back': '← Wróć do portfolio',
        'notfound.title': '404 - Nie znaleziono pliku',
        'notfound.body': 'Ta strona nie istnieje. Może została usunięta, a może nigdy jej nie było.',
        'section.interests': 'Zainteresowania',
        'cv.profile': 'Profil',
        'cv.contact': 'Kontakt',
        'cv.portfolio': 'Portfolio',
        'cv.consent': 'Wyrażam zgodę na przetwarzanie moich danych osobowych dla potrzeb niezbędnych do realizacji procesu rekrutacji (zgodnie z Rozporządzeniem Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE - RODO).',
        'printer.status': 'Drukowanie strony 1 z 1…',
        'printer.done': 'Drukowanie zakończone. CV jest gotowe.',
        'printer.cancelled': 'Drukowanie anulowane.',
        'printer.open': 'Otwórz CV',
        'printer.cancel': 'Anuluj',
        'printer.model': 'DOT-MATRIX 24',

        'browser.placeholder': 'Wpisz adres, link do YouTube albo słowa do wyszukania…',
        'browser.go': 'Idź',
        'browser.timeMachine': 'Wehikuł czasu',
        'browser.live': 'Internet na żywo',
        'browser.archived': 'Ta strona nie pozwala wyświetlać się wewnątrz innych stron, więc to jej najnowsza kopia z Wayback Machine.',
        'browser.archivedYear': 'Wehikuł czasu: przeglądasz internet tak, jak wyglądał w {year} roku.',
        'browser.openLive': 'Otwórz stronę na żywo ↗',
        'browser.loading': 'Otwieram {host}…',
        'browser.done': 'Gotowe',
        'browser.openedApp': 'Otwarto w aplikacji {app}.',
        'browser.back': 'Wstecz',
        'browser.forward': 'Dalej',
        'browser.refresh': 'Odśwież',
        'browser.home': 'Strona główna',
        'home.welcome': 'Witaj na stronie domowej: {name}!',
        'home.marquee': '★ Dzięki za odwiedziny! ★ Najlepiej oglądać w Internet 3.1 przy 800×600 ★ Wpisz się do księgi gości w Contact.exe ★ Żadne ciasteczko nie ucierpiało ★',
        'home.construction': 'STRONA W BUDOWIE',
        'home.visitor': 'Odwiedziłeś tę stronę',
        'home.times': 'razy',
        'home.about': 'O mnie',
        'home.projects': 'Moje projekty',
        'home.cool': 'Fajne linki',
        'home.search': 'Szukaj w Wikipedii',
        'home.searchButton': 'Szukaj',
        'home.tip': 'Wskazówka: wklej do paska adresu link z YouTube, Spotify albo Vimeo, albo wybierz rok w Wehikule czasu.',
        'home.updated': 'Ostatnia aktualizacja',
        'home.email': 'Napisz do mnie',
        'home.webring': 'Webring PortfolioOS',
        'home.random': 'Losowy artykuł z Wikipedii',
        'home.google99': 'Google w 1999',
        'home.yahoo96': 'Yahoo! w 1996',
        'home.spacejam': 'Space Jam (1996)',
        'home.youtube05': 'YouTube w 2005'
    }
};

export default STRINGS;
